# Для пользователя



Запустите ячейку ниже и вводите ваши данные

Для завершения ввода необходимо ввести пустую строку


In [71]:
#Пользователь должен через Enter вводить свои строки.
list = []
tmp = input()
while tmp:
  list.append(tmp)
  tmp = input()
User_X = list
User_X

123
123



['123', '123']

# 1. Обработка файлов

In [5]:
import pandas as pd

In [24]:
import requests
from bs4 import BeautifulSoup

# Функция для загрузки HTML-страницы и извлечения текста
def load_and_extract_text(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        text = soup.get_text()
        return text
    except Exception as e:
        print(f"Произошла ошибка при загрузке или обработке страницы: {e}")
        return None

# Функция для разделения текста на строки из 150 слов
def split_text_into_lines(text, max_words_per_line=133):
    words = text.split()
    lines = []
    current_line = ""

    for word in words:
        if len(current_line.split()) < max_words_per_line:
            current_line += word + " "
        else:
            lines.append(current_line.strip())
            current_line = word + " "

    if current_line:
        lines.append(current_line.strip())

    return lines

In [25]:
lines_sum_without_html = []
lines_sum_with_html = []
adreses = ['https://www.w3.org/International/articles/serving-xhtml/index.ru.html',
          'https://webstool.ru/laravel-ru-lang.html',
          'https://kotlinlang.ru/docs/lambdas.html',
          'https://remoteplay.dl.playstation.net/remoteplay/lang/ru/index.html',
          'https://github.com/rust-lang-ru/rustycrate.ru/blob/master/articles-education.html',
          'http://pro-lang.ru/novosti.html',
          'https://doc.rust-lang.ru/book/ch03-03-how-functions-work.html',
          'http://nmr.ioc.ac.ru/First_Info.html',
          'http://www.tehsovet.ru/news-4092.html',
          'https://lk.fss.ru/FAQ.html',
          'https://www.ilo.org/moscow/areas-of-work/occupational-safety-and-health/WCMS_305901/lang--ru/index.htm',
          'https://www.nic.ru/help/format-zagolovka-zaprosa_3585.html',
          'https://vestiprim.ru/livettv/135961-transljacija-kruglosutochno-kamery-ustanovleny-u-puteprovoda-v-rajone-kiparisovo.html',
          'https://vestiprim.ru/livettv/135961-transljacija-kruglosutochno-kamery-ustanovleny-u-puteprovoda-v-rajone-kiparisovo.html',
          'https://www.nic.ru/help/ru-rf-su-domeny-3-go-urovnya_3600.html',
          'https://codeguide.academy/html-css.html',
          'https://docs.scala-lang.org/ru/tour/tour-of-scala.html',
          'https://west-ru.ru/ru/services/manufacturing-systems/components/lang-tube-tec.html',
          'https://valaam.com/ru/kontakty.html',
          'http://csppm.ru/nashe_podmoskovie.html',
          'https://www.fragrantica.ru/designers/Ulrich-Lang.html',
          'https://boscooutlet.ru/brands/woman/helmut-lang.html',
          'https://www.ukraine.com.ua/uk/forum/seo/yazikovie-versii-sajta-kak-pra.html',
          'https://www.freenom.com/ru/index.html']

for url in adreses:
    text = load_and_extract_text(url)
    lines_with_html = split_text_into_lines(text, max_words_per_line=133)
    lines_without_html = [BeautifulSoup(line, 'html.parser').get_text() for line in lines_with_html]

    lines_sum_without_html += lines_without_html
    lines_sum_with_html += lines_with_html

print(len(lines_sum_without_html), len(lines_sum_with_html))

188 188


In [26]:
X = pd.read_csv('raw_labels_50.csv')
Y = pd.read_csv('true_labels_50.csv')

In [27]:
print(X.head(1))
print(Y.head(1))

                                Неправильный вариант
0  Этапы отбора:1. Подача заявок (до 19 июня);2. ...
                                  Правильный вариант
0  <ul>\n  <li><b>Этапы отбора:</b></li>\n  <li>1...


In [28]:
def dataframe_strings(df):
    return [df.iloc[i][0] for i in range(df.shape[0])]

X_text = dataframe_strings(X)
Y_text = dataframe_strings(Y)
print(X_text[0])
print([Y_text[0]])

Этапы отбора:1. Подача заявок (до 19 июня);2. Онлайн тестирование на личностные качества (до 22 июня);3. Интервью по компетенциям (до 30 июня).
['<ul>\n  <li><b>Этапы отбора:</b></li>\n  <li>1. Подача заявок (до 19 июня);</li>\n  <li>2. Онлайн тестирование на личностные качества (до 22 июня);</li>\n  <li>3. Интервью по компетенциям (до 30 июня).</li>\n</ul>']


In [29]:
Y_100 = ' '.join(Y_text)
Y_100_text = split_text_into_lines(Y_100)
X_100_text = [BeautifulSoup(line, 'html.parser').get_text() for line in Y_100_text]
print(Y_100_text[0])
print()
print(X_100_text[0])

<ul> <li><b>Этапы отбора:</b></li> <li>1. Подача заявок (до 19 июня);</li> <li>2. Онлайн тестирование на личностные качества (до 22 июня);</li> <li>3. Интервью по компетенциям (до 30 июня).</li> </ul> <p>По всем вопросам вы можете обращаться по эл. почте <b>mobility@avcrf.ru</b>, в теме письма необходимо указать <b>«Лаборатория экотроп. Байкальск»</b></p> <p>Некоторые из волонтерских задач:</p> <ol> <li>Привлечение заинтересованных лиц и организаций, а также лидеров общественного мнения к поддержке инициатив проекта.</li> <li>Взаимодействие с партнерами проекта, участие в партнерских мероприятиях.</li> <li>Сопровождение деловых, научных, культурно-массовых и просветительских мероприятий.</li> <li>Обеспечение информационной поддержки проекта.</li> <li>Популяризация инициатив проекта.</li> </ol> <p><b>Обязательными требованиями к волонтерам являются:</b></p> <ul> <li>возраст кандидата не менее 18 лет (на момент подачи заявки);</li> <li>гражданство Российской Федерации;</li> <li>владение 

Вычисление расстояния Левенштейна

In [30]:
%%capture
!pip install python-Levenshtein
import Levenshtein

In [31]:
# X, Y - lists of strings
def Levenshtein_metric(X, Y):
    sum_levenshtein_distance = 0
    for i in range(len(X)):
        distance = Levenshtein.distance(X[0], Y[0])
        sum_levenshtein_distance += distance

    return sum_levenshtein_distance


Levenshtein_metric(X_text, Y_text)

3250

In [32]:
def count_of_symbols(list_of_strings):
    sum_len_strs = 0

    for i in range(len(list_of_strings)):
        sum_len_strs += len(str(list_of_strings[i]))

    return sum_len_strs

print(count_of_symbols(X_text), count_of_symbols(Y_text))

13985 17709


# 2. Tokenization

In [33]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [34]:
# Инициализируем токенизатор для обработки текста
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(X_text + Y_text + User_X)

In [35]:
# Подготавливаем данные для обучения
source_sequences = tokenizer.texts_to_sequences(X_text)
target_sequences = tokenizer.texts_to_sequences(Y_text)
user_sequences = tokenizer.texts_to_sequences(User_X)
print(source_sequences[0])
print(target_sequences[0])

[813, 814, 204, 79, 12, 205, 815, 206, 80, 3, 81, 82, 12, 83, 816, 207, 4, 208, 12, 209, 817]
[23, 1098, 1099, 1100, 204, 79, 12, 205, 199, 1101, 206, 80, 3, 81, 82, 12, 83, 199, 1102, 207, 4, 208, 12, 209, 1103]


In [36]:
# Определяем максимальную длину последовательности
max_sequence_length = max(len(seq) for seq in source_sequences+target_sequences+user_sequences)

# Дополняем последовательности до максимальной длины
source_pad = pad_sequences(source_sequences, maxlen=max_sequence_length, padding='post')
target_pad = pad_sequences(target_sequences, maxlen=max_sequence_length, padding='post')
user_pad = pad_sequences(user_sequences, maxlen=max_sequence_length, padding='post')

print(source_pad[0])
print(target_pad[0])

[813 814 204  79  12 205 815 206  80   3  81  82  12  83 816 207   4 208
  12 209 817   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0]
[  23 1098 1099 1100  204   79   12  205  199 1101  206   80    3   81
   82   12   83  199 1102  207    4  208   12  209 1103    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0   

In [37]:
# Создаем модель RNN
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=16, input_length=max_sequence_length),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.word_index) + 1, activation='softmax')
])

# Компилируем модель
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Обучаем модель на исходных и целевых последовательностях
model.fit(source_pad, target_pad, epochs=10, verbose=2)

Epoch 1/10
2/2 - 4s - loss: 7.3031 - accuracy: 7.5188e-04 - 4s/epoch - 2s/step
Epoch 2/10
2/2 - 1s - loss: 7.2968 - accuracy: 0.2517 - 609ms/epoch - 304ms/step
Epoch 3/10
2/2 - 1s - loss: 7.2901 - accuracy: 0.7266 - 559ms/epoch - 279ms/step
Epoch 4/10
2/2 - 1s - loss: 7.2830 - accuracy: 0.7275 - 518ms/epoch - 259ms/step
Epoch 5/10
2/2 - 1s - loss: 7.2750 - accuracy: 0.7277 - 730ms/epoch - 365ms/step
Epoch 6/10
2/2 - 1s - loss: 7.2649 - accuracy: 0.7275 - 966ms/epoch - 483ms/step
Epoch 7/10
2/2 - 1s - loss: 7.2520 - accuracy: 0.7275 - 1s/epoch - 501ms/step
Epoch 8/10
2/2 - 1s - loss: 7.2344 - accuracy: 0.7275 - 752ms/epoch - 376ms/step
Epoch 9/10
2/2 - 1s - loss: 7.2096 - accuracy: 0.7275 - 668ms/epoch - 334ms/step
Epoch 10/10
2/2 - 1s - loss: 7.1717 - accuracy: 0.7275 - 567ms/epoch - 284ms/step


In [38]:
# Проверяем работу модели на примере
input_text = [X_text[0]]

# Преобразуем входной текст в последовательность чисел
input_test = tokenizer.texts_to_sequences(input_text)
input_test_pad = pad_sequences(input_test, maxlen=max_sequence_length, padding='post')

# Получаем предсказание от модели
predicted_sequence = model.predict(input_test_pad)

predicted_sequence

1/1 [==============================] - 1s 1s/step


array([[[0.00070457, 0.00070463, 0.00070398, ..., 0.00067228,
         0.00067288, 0.00067399],
        [0.00070795, 0.00070706, 0.00070623, ..., 0.00067127,
         0.00067343, 0.00067428],
        [0.00071146, 0.0007113 , 0.00070938, ..., 0.00067068,
         0.00067253, 0.00067476],
        ...,
        [0.00086725, 0.0008025 , 0.0008335 , ..., 0.00065167,
         0.00068087, 0.00069224],
        [0.00086726, 0.0008025 , 0.00083351, ..., 0.00065167,
         0.00068087, 0.00069224],
        [0.00086726, 0.0008025 , 0.00083351, ..., 0.00065167,
         0.00068087, 0.00069224]]], dtype=float32)

In [39]:
tf.argmax(predicted_sequence, axis=2)

<tf.Tensor: shape=(1, 133), dtype=int64, numpy=
array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]])>

In [40]:
#Из тензора с токенами в слова
import numpy as np
def tensor_to_text(tensor):
    return tokenizer.sequences_to_texts([[np.array(arr[1:]).argmax() for arr in tensor_1] for tensor_1 in tensor])

tensor_to_text(predicted_sequence)

['в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в']

In [41]:
Y_1 = model(source_pad)
Y_1_text = tensor_to_text(Y_1)
print(Y_1_text[0])

в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в в


In [42]:
Levenshtein_metric(Y_1_text, Y_text)

11150

#3. Эксперименты с loses

In [43]:
len(tokenizer.word_index)

1482

In [44]:
# Создаем модель RNN
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=16, input_length=max_sequence_length),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.word_index) + 1, activation='softmax')#,
    # tf.keras.layers.Lambda(lambda x: tf.argmax(x, axis=2)),
    # tf.keras.layers.Lambda(lambda x: tokenizer.sequences_to_texts(np.array(x)))
])

In [45]:
# Компилируем модель
loss = tf.losses.SparseCategoricalCrossentropy()
model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])

In [46]:
# Обучаем модель на исходных и целевых последовательностях
model.fit(np.array(source_pad, dtype='int64'), np.round(target_pad).astype('int64'), epochs=10, verbose=2)

Epoch 1/10
2/2 - 7s - loss: 7.3045 - accuracy: 6.0150e-04 - 7s/epoch - 3s/step
Epoch 2/10
2/2 - 1s - loss: 7.2974 - accuracy: 0.0298 - 1s/epoch - 520ms/step
Epoch 3/10
2/2 - 1s - loss: 7.2905 - accuracy: 0.7280 - 1s/epoch - 578ms/step
Epoch 4/10
2/2 - 1s - loss: 7.2833 - accuracy: 0.7275 - 738ms/epoch - 369ms/step
Epoch 5/10
2/2 - 1s - loss: 7.2752 - accuracy: 0.7275 - 593ms/epoch - 296ms/step
Epoch 6/10
2/2 - 1s - loss: 7.2658 - accuracy: 0.7275 - 632ms/epoch - 316ms/step
Epoch 7/10
2/2 - 1s - loss: 7.2542 - accuracy: 0.7275 - 613ms/epoch - 307ms/step
Epoch 8/10
2/2 - 1s - loss: 7.2393 - accuracy: 0.7275 - 582ms/epoch - 291ms/step
Epoch 9/10
2/2 - 1s - loss: 7.2189 - accuracy: 0.7275 - 569ms/epoch - 284ms/step
Epoch 10/10
2/2 - 1s - loss: 7.1884 - accuracy: 0.7275 - 742ms/epoch - 371ms/step


In [47]:
np.array(target_pad, dtype='int64')[0]

array([  23, 1098, 1099, 1100,  204,   79,   12,  205,  199, 1101,  206,
         80,    3,   81,   82,   12,   83,  199, 1102,  207,    4,  208,
         12,  209, 1103,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0])

In [48]:
# Инициализируем токенизатор для обработки текста
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(X_text + Y_text + User_X + lines_sum_without_html + lines_sum_with_html)

# Подготавливаем данные для обучения
source_sequences = tokenizer.texts_to_sequences(X_text + lines_sum_without_html)
user_sequences = tokenizer.texts_to_sequences(User_x + lines_sum_without_html)
target_sequences = tokenizer.texts_to_sequences(Y_text + lines_sum_with_html)

# Определяем максимальную длину последовательности
max_sequence_length = max(len(seq) for seq in source_sequences+target_sequences+user_sequences)

# Дополняем последовательности до максимальной длины
source_pad = pad_sequences(source_sequences, maxlen=max_sequence_length, padding='post')
user_pad = pad_sequences(user_sequences, maxlen=max_sequence_length, padding='post')
target_pad = pad_sequences(target_sequences, maxlen=max_sequence_length, padding='post')

In [49]:
# Создаем модель RNN
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=16, input_length=max_sequence_length),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.word_index) + 1, activation='softmax')#,
    # tf.keras.layers.Lambda(lambda x: tf.argmax(x, axis=2)),
    # tf.keras.layers.Lambda(lambda x: tokenizer.sequences_to_texts(np.array(x)))
])

# Компилируем модель
loss = tf.losses.SparseCategoricalCrossentropy()
model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])

# Обучаем модель на исходных и целевых последовательностях
model.fit(np.array(source_pad, dtype='int64'), np.round(target_pad).astype('int64'), epochs=10, verbose=2)

Epoch 1/10
8/8 - 12s - loss: 9.3061 - accuracy: 0.0881 - 12s/epoch - 1s/step
Epoch 2/10
8/8 - 9s - loss: 9.2958 - accuracy: 0.2094 - 9s/epoch - 1s/step
Epoch 3/10
8/8 - 8s - loss: 9.2743 - accuracy: 0.2079 - 8s/epoch - 1s/step
Epoch 4/10
8/8 - 10s - loss: 9.1746 - accuracy: 0.2076 - 10s/epoch - 1s/step
Epoch 5/10
8/8 - 16s - loss: 8.9490 - accuracy: 0.2076 - 16s/epoch - 2s/step
Epoch 6/10
8/8 - 13s - loss: 8.7247 - accuracy: 0.2076 - 13s/epoch - 2s/step
Epoch 7/10
8/8 - 10s - loss: 8.5004 - accuracy: 0.2076 - 10s/epoch - 1s/step
Epoch 8/10
8/8 - 10s - loss: 8.2913 - accuracy: 0.2076 - 10s/epoch - 1s/step
Epoch 9/10
8/8 - 9s - loss: 8.0962 - accuracy: 0.2076 - 9s/epoch - 1s/step
Epoch 10/10
8/8 - 10s - loss: 7.9367 - accuracy: 0.2076 - 10s/epoch - 1s/step


In [50]:
import requests

response = requests.get('https://raw.githubusercontent.com/danakt/russian-words/master/russian.txt')

text = response.content.decode('cp1251')

with open('russian.txt', 'wb') as ru:
    ru.write(text.encode('utf-8'))

response = requests.get('https://raw.githubusercontent.com/danakt/russian-words/master/russian_surnames.txt')

text = response.content.decode('cp1251')

with open('russian_surnames.txt', 'wb') as ru:
    ru.write(text.encode('utf-8'))

# 4. Обработка приватного датасета

In [51]:
hak = pd.read_csv('raw_labels_150.csv')
hak_text = dataframe_strings(hak)

# Инициализируем токенизатор для обработки текста
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(hak_text)

# Подготавливаем данные для обучения
source_hak = tokenizer.texts_to_sequences(hak_text)

# Определяем максимальную длину последовательности
max_sequence_length = 133

# Дополняем последовательности до максимальной длины
hak_pad = pad_sequences(source_hak, maxlen=max_sequence_length, padding='post')

hak_pad

array([[ 196,  311,  312, ...,    0,    0,    0],
       [  40,  322,   17, ...,    0,    0,    0],
       [ 106,  202,   20, ...,    0,    0,    0],
       ...,
       [2414,   54, 2415, ...,    0,    0,    0],
       [ 372,   24, 2425, ...,    0,    0,    0],
       [2433, 2434, 2435, ...,    0,    0,    0]], dtype=int32)

In [52]:
hak_predict = model.predict(hak_pad)
hak_text = tensor_to_text(hak_predict)
len(hak_text)

5/5 [==============================] - 2s 298ms/step


150

In [53]:
pd.DataFrame(hak_text).to_csv ('answer.csv', index= False )

# Ровно по 100 слов если сделать

In [72]:
# Инициализируем токенизатор для обработки текста
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(X_100_text + Y_100_text + User_X)

# Подготавливаем данные для обучения
source_100 = tokenizer.texts_to_sequences(X_100_text)
target_100 = tokenizer.texts_to_sequences(Y_100_text)

# Определяем максимальную длину последовательности
max_sequence_length = max(len(seq) for seq in source_100+target_100)

# Дополняем последовательности до максимальной длины
source_100_pad = pad_sequences(source_100, maxlen=max_sequence_length, padding='post')
target_100_pad = pad_sequences(target_100, maxlen=max_sequence_length, padding='post')

In [73]:
# Создаем модель RNN
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=16, input_length=max_sequence_length),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.word_index) + 1, activation='softmax')#,
    # tf.keras.layers.Lambda(lambda x: tf.argmax(x, axis=2)),
    # tf.keras.layers.Lambda(lambda x: tokenizer.sequences_to_texts(np.array(x)))
])

# Компилируем модель
loss = tf.losses.SparseCategoricalCrossentropy()
# Adadelta - бан, 0
# Adagrad - 0.0361
model.compile(optimizer='Adagrad', loss=loss, metrics=['accuracy'])

# Обучаем модель на исходных и целевых последовательностях
model.fit(np.array(source_100_pad, dtype='int64'), np.round(target_100_pad).astype('int64'), epochs=2000, verbose=2)
model.save('/content/my_model.keras')

Epoch 1/2000


KeyboardInterrupt: ignored

# Использование модели



In [87]:
User_pred = []
for row in User_X:
  seq = tokenizer.texts_to_sequences(row)
  pad_seq = pad_sequences(seq, maxlen=max_sequence_length, padding='post')
  pred = tensor_to_text(model.predict(pad_seq))[0]
  User_pred.append(pred)
User_df = pd.DataFrame(User_pred, columns=['Вывод'])
User_df.to_csv('output.csv')

1/1 [==============================] - 0s 67ms/step
могиле <p>по <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит <li>ответит

Ваши ответы лежат в файле output.csv
