# Для пользователя



Запустите ячейку ниже и вводите ваши данные

Для завершения ввода необходимо ввести пустую строку


In [2]:
#Пользователь должен через Enter вводить свои строки.
list = []
tmp = input()
while tmp:
  list.append(tmp)
  tmp = input()
User_X = list
User_X

['Всем привет']

Далее запустите все ячейки ниже, не разворачивая их

# 1. Обработка файлов

In [5]:
%%capture
%pip install pandas
import pandas as pd

In [6]:
import requests
from bs4 import BeautifulSoup

# Функция для загрузки HTML-страницы и извлечения текста
def load_and_extract_text(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        text = soup.get_text()
        return text
    except Exception as e:
        print(f"Произошла ошибка при загрузке или обработке страницы: {e}")
        return None

# Функция для разделения текста на строки из 150 слов
def split_text_into_lines(text, max_words_per_line=133):
    words = text.split()
    lines = []
    current_line = ""

    for word in words:
        if len(current_line.split()) < max_words_per_line:
            current_line += word + " "
        else:
            lines.append(current_line.strip())
            current_line = word + " "

    if current_line:
        lines.append(current_line.strip())

    return lines

In [7]:
lines_sum_without_html = []
lines_sum_with_html = []
adreses = ['https://www.w3.org/International/articles/serving-xhtml/index.ru.html',
          'https://webstool.ru/laravel-ru-lang.html',
          'https://kotlinlang.ru/docs/lambdas.html',
          'https://remoteplay.dl.playstation.net/remoteplay/lang/ru/index.html',
          'https://github.com/rust-lang-ru/rustycrate.ru/blob/master/articles-education.html',
          'http://pro-lang.ru/novosti.html',
          'https://doc.rust-lang.ru/book/ch03-03-how-functions-work.html',
          'http://nmr.ioc.ac.ru/First_Info.html',
          'http://www.tehsovet.ru/news-4092.html',
          'https://lk.fss.ru/FAQ.html',
          'https://www.ilo.org/moscow/areas-of-work/occupational-safety-and-health/WCMS_305901/lang--ru/index.htm',
          'https://www.nic.ru/help/format-zagolovka-zaprosa_3585.html',
          'https://vestiprim.ru/livettv/135961-transljacija-kruglosutochno-kamery-ustanovleny-u-puteprovoda-v-rajone-kiparisovo.html',
          'https://vestiprim.ru/livettv/135961-transljacija-kruglosutochno-kamery-ustanovleny-u-puteprovoda-v-rajone-kiparisovo.html',
          'https://www.nic.ru/help/ru-rf-su-domeny-3-go-urovnya_3600.html',
          'https://codeguide.academy/html-css.html',
          'https://docs.scala-lang.org/ru/tour/tour-of-scala.html',
          'https://west-ru.ru/ru/services/manufacturing-systems/components/lang-tube-tec.html',
          'https://valaam.com/ru/kontakty.html',
          'http://csppm.ru/nashe_podmoskovie.html',
          'https://www.fragrantica.ru/designers/Ulrich-Lang.html',
          'https://boscooutlet.ru/brands/woman/helmut-lang.html',
          'https://www.ukraine.com.ua/uk/forum/seo/yazikovie-versii-sajta-kak-pra.html',
          'https://www.freenom.com/ru/index.html']

for url in adreses:
    text = load_and_extract_text(url)
    lines_with_html = split_text_into_lines(text, max_words_per_line=133)
    lines_without_html = [BeautifulSoup(line, 'html.parser').get_text() for line in lines_with_html]

    lines_sum_without_html += lines_without_html
    lines_sum_with_html += lines_with_html

print(len(lines_sum_without_html), len(lines_sum_with_html))

188 188


In [10]:
X = pd.read_csv('raw_labels_50.csv')
Y = pd.read_csv('true_labels_50.csv')

In [13]:
%%capture
%pip install pyaspeller
from pyaspeller import YandexSpeller

speller = YandexSpeller()

def spell_check_and_correct(text):
    corrected_text = speller.spelled(text)
    return corrected_text

In [14]:
print(X.head(1))
print(Y.head(1))

                                Неправильный вариант
0  Этапы отбора:1. Подача заявок (до 19 июня);2. ...
                                  Правильный вариант
0  <ul>\n  <li><b>Этапы отбора:</b></li>\n  <li>1...


In [15]:
def dataframe_strings(df):
    return [spell_check_and_correct(df.iloc[i][0]) for i in range(df.shape[0])]

X_text = dataframe_strings(X)
Y_text = dataframe_strings(Y)
User_X = [spell_check_and_correct(row) for row in User_X]
print(X_text[0])
print([Y_text[0]])

Этапы отбора:1. Подача заявок (до 19 июня);2. Онлайн тестирование на личностные качества (до 22 июня);3. Интервью по компетенциям (до 30 июня).
['<<ул>\n  <li><b>Этапы отбора:</b></li>\n  <li>1. Подача заявок (до 19 июня);</li>\n  <li>2. Онлайн тестирование на личностные качества (до 22 июня);</li>\n  <li>3. Интервью по компетенциям (до 30 июня).</li>\n</<ул>']


In [16]:
Y_100 = ' '.join(Y_text)
Y_100_text = split_text_into_lines(Y_100)
X_100_text = [BeautifulSoup(line, 'html.parser').get_text() for line in Y_100_text]
print(Y_100_text[0])
print()
print(X_100_text[0])

<<ул> <li><b>Этапы отбора:</b></li> <li>1. Подача заявок (до 19 июня);</li> <li>2. Онлайн тестирование на личностные качества (до 22 июня);</li> <li>3. Интервью по компетенциям (до 30 июня).</li> </<ул> <p>По всем вопросам вы можете обращаться по эл. почте <b>mobility@avcrf.ru</b>, в теме письма необходимо указать <b>«Лаборатория экотроп. Байкальск»</b></p> <p>Некоторые из волонтерских задач:</p> <ol> <li>Привлечение заинтересованных лиц и организаций, а также лидеров общественного мнения к поддержке инициатив проекта.</li> <li>Взаимодействие с партнерами проекта, участие в партнерских мероприятиях.</li> <li>Сопровождение деловых, научных, культурно-массовых и просветительских мероприятий.</li> <li>Обеспечение информационной поддержки проекта.</li> <li>Популяризация инициатив проекта.</li> </ol> <p><b>Обязательными требованиями к волонтерам являются:</b></p> <<ул> <li>возраст кандидата не менее 18 лет (на момент подачи заявки);</li> <li>гражданство Российской Федерации;</li> <li>владен

Вычисление расстояния Левенштейна

In [17]:
%%capture
%pip install python-Levenshtein
import Levenshtein

In [18]:
# X, Y - lists of strings
def Levenshtein_metric(X, Y):
    sum_levenshtein_distance = 0
    for i in range(len(X)):
        distance = Levenshtein.distance(X[0], Y[0])
        sum_levenshtein_distance += distance

    return sum_levenshtein_distance


Levenshtein_metric(X_text, Y_text)

3350

In [19]:
def count_of_symbols(list_of_strings):
    sum_len_strs = 0

    for i in range(len(list_of_strings)):
        sum_len_strs += len(str(list_of_strings[i]))

    return sum_len_strs

print(count_of_symbols(X_text), count_of_symbols(Y_text))

13994 17844


# 2. Tokenization

In [20]:
%%capture
%pip install tensorflow
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

KeyboardInterrupt: 

In [ ]:
# Инициализируем токенизатор для обработки текста
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(X_text + Y_text + User_X)

In [ ]:
# Подготавливаем данные для обучения
source_sequences = tokenizer.texts_to_sequences(X_text)
target_sequences = tokenizer.texts_to_sequences(Y_text)
user_sequences = tokenizer.texts_to_sequences(User_X)
print(source_sequences[0])
print(target_sequences[0])

[814, 815, 206, 80, 12, 207, 816, 208, 81, 3, 82, 83, 12, 84, 817, 209, 4, 210, 12, 211, 818]
[23, 1099, 1100, 1101, 206, 80, 12, 207, 201, 1102, 208, 81, 3, 82, 83, 12, 84, 201, 1103, 209, 4, 210, 12, 211, 1104]


In [ ]:
# Определяем максимальную длину последовательности
max_sequence_length = max(len(seq) for seq in source_sequences+target_sequences+user_sequences)

# Дополняем последовательности до максимальной длины
source_pad = pad_sequences(source_sequences, maxlen=max_sequence_length, padding='post')
target_pad = pad_sequences(target_sequences, maxlen=max_sequence_length, padding='post')
user_pad = pad_sequences(user_sequences, maxlen=max_sequence_length, padding='post')

print(source_pad[0])
print(target_pad[0])

[814 815 206  80  12 207 816 208  81   3  82  83  12  84 817 209   4 210
  12 211 818   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0]
[  23 1099 1100 1101  206   80   12  207  201 1102  208   81    3   82
   83   12   84  201 1103  209    4  210   12  211 1104    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0   

# 3. Создание модели

In [ ]:
# Создаем модель RNN
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=16, input_length=max_sequence_length),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.word_index) + 1, activation='softmax')
])

# Компилируем модель
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Обучаем модель на исходных и целевых последовательностях
model.fit(source_pad, target_pad, epochs=10, verbose=2)

Epoch 1/10
2/2 - 4s - loss: 7.3037 - accuracy: 4.5113e-04 - 4s/epoch - 2s/step
Epoch 2/10
2/2 - 0s - loss: 7.2952 - accuracy: 0.2507 - 327ms/epoch - 163ms/step
Epoch 3/10
2/2 - 1s - loss: 7.2853 - accuracy: 0.7283 - 506ms/epoch - 253ms/step
Epoch 4/10
2/2 - 0s - loss: 7.2737 - accuracy: 0.7278 - 495ms/epoch - 248ms/step
Epoch 5/10
2/2 - 1s - loss: 7.2590 - accuracy: 0.7275 - 513ms/epoch - 257ms/step
Epoch 6/10
2/2 - 1s - loss: 7.2398 - accuracy: 0.7275 - 565ms/epoch - 283ms/step
Epoch 7/10
2/2 - 1s - loss: 7.2131 - accuracy: 0.7275 - 622ms/epoch - 311ms/step
Epoch 8/10
2/2 - 1s - loss: 7.1746 - accuracy: 0.7275 - 538ms/epoch - 269ms/step
Epoch 9/10
2/2 - 1s - loss: 7.1168 - accuracy: 0.7275 - 736ms/epoch - 368ms/step
Epoch 10/10
2/2 - 1s - loss: 7.0335 - accuracy: 0.7275 - 1s/epoch - 569ms/step


In [ ]:
# Проверяем работу модели на примере
input_text = [X_text[0]]

# Преобразуем входной текст в последовательность чисел
input_test = tokenizer.texts_to_sequences(input_text)
input_test_pad = pad_sequences(input_test, maxlen=max_sequence_length, padding='post')

# Получаем предсказание от модели
predicted_sequence = model.predict(input_test_pad)

predicted_sequence

1/1 [==============================] - 1s 888ms/step


array([[[0.0007017 , 0.00069835, 0.00069946, ..., 0.00066915,
         0.00066818, 0.00066819],
        [0.00070599, 0.00070011, 0.00070168, ..., 0.00066853,
         0.00066812, 0.00066762],
        [0.00071395, 0.00070321, 0.00070632, ..., 0.00066839,
         0.00066753, 0.00066688],
        ...,
        [0.00113239, 0.0008823 , 0.00091535, ..., 0.00065464,
         0.00063715, 0.0006359 ],
        [0.0011324 , 0.0008823 , 0.00091535, ..., 0.00065464,
         0.00063715, 0.0006359 ],
        [0.0011324 , 0.0008823 , 0.00091535, ..., 0.00065464,
         0.00063715, 0.0006359 ]]], dtype=float32)

In [ ]:
tf.argmax(predicted_sequence, axis=2)

<tf.Tensor: shape=(1, 133), dtype=int64, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]])>

In [ ]:
#Из тензора с токенами в слова
import numpy as np
def tensor_to_text(tensor):
    return tokenizer.sequences_to_texts([[np.array(arr[1:]).argmax() for arr in tensor_1] for tensor_1 in tensor])

tensor_to_text(predicted_sequence)

['в и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и']

In [ ]:
Y_1 = model(source_pad)
Y_1_text = tensor_to_text(Y_1)
print(Y_1_text[0])

в и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и и


In [ ]:
Levenshtein_metric(Y_1_text, Y_text)

11500

#3. Эксперименты с loses

In [ ]:
len(tokenizer.word_index)

1492

In [ ]:
# Создаем модель RNN
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=16, input_length=max_sequence_length),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.word_index) + 1, activation='softmax')#,
    # tf.keras.layers.Lambda(lambda x: tf.argmax(x, axis=2)),
    # tf.keras.layers.Lambda(lambda x: tokenizer.sequences_to_texts(np.array(x)))
])

In [ ]:
# Компилируем модель
loss = tf.losses.SparseCategoricalCrossentropy()
model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])

In [ ]:
# Обучаем модель на исходных и целевых последовательностях
model.fit(np.array(source_pad, dtype='int64'), np.round(target_pad).astype('int64'), epochs=10, verbose=2)

Epoch 1/10
2/2 - 6s - loss: 7.3048 - accuracy: 9.0226e-04 - 6s/epoch - 3s/step
Epoch 2/10
2/2 - 1s - loss: 7.2973 - accuracy: 0.2738 - 586ms/epoch - 293ms/step
Epoch 3/10
2/2 - 1s - loss: 7.2891 - accuracy: 0.7277 - 505ms/epoch - 252ms/step
Epoch 4/10
2/2 - 1s - loss: 7.2797 - accuracy: 0.7275 - 510ms/epoch - 255ms/step
Epoch 5/10
2/2 - 1s - loss: 7.2685 - accuracy: 0.7275 - 599ms/epoch - 300ms/step
Epoch 6/10
2/2 - 1s - loss: 7.2547 - accuracy: 0.7275 - 599ms/epoch - 299ms/step
Epoch 7/10
2/2 - 1s - loss: 7.2365 - accuracy: 0.7275 - 614ms/epoch - 307ms/step
Epoch 8/10
2/2 - 1s - loss: 7.2101 - accuracy: 0.7275 - 860ms/epoch - 430ms/step
Epoch 9/10
2/2 - 1s - loss: 7.1739 - accuracy: 0.7275 - 939ms/epoch - 469ms/step
Epoch 10/10
2/2 - 1s - loss: 7.1181 - accuracy: 0.7275 - 1s/epoch - 585ms/step


In [ ]:
np.array(target_pad, dtype='int64')[0]

array([  23, 1099, 1100, 1101,  206,   80,   12,  207,  201, 1102,  208,
         81,    3,   82,   83,   12,   84,  201, 1103,  209,    4,  210,
         12,  211, 1104,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0])

In [ ]:
# Инициализируем токенизатор для обработки текста
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(X_text + Y_text + User_X + lines_sum_without_html + lines_sum_with_html)

# Подготавливаем данные для обучения
source_sequences = tokenizer.texts_to_sequences(X_text + lines_sum_without_html)
user_sequences = tokenizer.texts_to_sequences(User_X + lines_sum_without_html)
target_sequences = tokenizer.texts_to_sequences(Y_text + lines_sum_with_html)

# Определяем максимальную длину последовательности
max_sequence_length = max(len(seq) for seq in source_sequences+target_sequences+user_sequences)

# Дополняем последовательности до максимальной длины
source_pad = pad_sequences(source_sequences, maxlen=max_sequence_length, padding='post')
user_pad = pad_sequences(user_sequences, maxlen=max_sequence_length, padding='post')
target_pad = pad_sequences(target_sequences, maxlen=max_sequence_length, padding='post')

In [ ]:
# Создаем модель RNN
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=16, input_length=max_sequence_length),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.word_index) + 1, activation='softmax')#,
    # tf.keras.layers.Lambda(lambda x: tf.argmax(x, axis=2)),
    # tf.keras.layers.Lambda(lambda x: tokenizer.sequences_to_texts(np.array(x)))
])

# Компилируем модель
loss = tf.losses.SparseCategoricalCrossentropy()
model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])

# Обучаем модель на исходных и целевых последовательностях
model.fit(np.array(source_pad, dtype='int64'), np.round(target_pad).astype('int64'), epochs=10, verbose=2)

Epoch 1/10
8/8 - 13s - loss: 9.3054 - accuracy: 0.1472 - 13s/epoch - 2s/step
Epoch 2/10
8/8 - 10s - loss: 9.2911 - accuracy: 0.2080 - 10s/epoch - 1s/step
Epoch 3/10
8/8 - 10s - loss: 9.2415 - accuracy: 0.2077 - 10s/epoch - 1s/step
Epoch 4/10
8/8 - 8s - loss: 9.0743 - accuracy: 0.2077 - 8s/epoch - 1s/step
Epoch 5/10
8/8 - 9s - loss: 8.8643 - accuracy: 0.2077 - 9s/epoch - 1s/step
Epoch 6/10
8/8 - 10s - loss: 8.6571 - accuracy: 0.2077 - 10s/epoch - 1s/step
Epoch 7/10
8/8 - 9s - loss: 8.4434 - accuracy: 0.2077 - 9s/epoch - 1s/step
Epoch 8/10
8/8 - 9s - loss: 8.2402 - accuracy: 0.2077 - 9s/epoch - 1s/step
Epoch 9/10
8/8 - 9s - loss: 8.0710 - accuracy: 0.2077 - 9s/epoch - 1s/step
Epoch 10/10
8/8 - 10s - loss: 7.9162 - accuracy: 0.2077 - 10s/epoch - 1s/step


In [ ]:
import requests

response = requests.get('https://raw.githubusercontent.com/danakt/russian-words/master/russian.txt')

text = response.content.decode('cp1251')

with open('russian.txt', 'wb') as ru:
    ru.write(text.encode('utf-8'))

response = requests.get('https://raw.githubusercontent.com/danakt/russian-words/master/russian_surnames.txt')

text = response.content.decode('cp1251')

with open('russian_surnames.txt', 'wb') as ru:
    ru.write(text.encode('utf-8'))

# 4. Обработка приватного датасета

In [ ]:
hak = pd.read_csv('raw_labels_150.csv')
hak_text = dataframe_strings(hak)

# Инициализируем токенизатор для обработки текста
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(hak_text)

# Подготавливаем данные для обучения
source_hak = tokenizer.texts_to_sequences(hak_text)

# Определяем максимальную длину последовательности
max_sequence_length = 133

# Дополняем последовательности до максимальной длины
hak_pad = pad_sequences(source_hak, maxlen=max_sequence_length, padding='post')

hak_pad

array([[ 196,  311,  312, ...,    0,    0,    0],
       [  40,  322,   17, ...,    0,    0,    0],
       [ 106,  202,   20, ...,    0,    0,    0],
       ...,
       [2414,   54, 2415, ...,    0,    0,    0],
       [ 372,   24, 2425, ...,    0,    0,    0],
       [2433, 2434, 2435, ...,    0,    0,    0]], dtype=int32)

In [ ]:
hak_predict = model.predict(hak_pad)
hak_text = tensor_to_text(hak_predict)
len(hak_text)

5/5 [==============================] - 3s 404ms/step


150

In [ ]:
pd.DataFrame(hak_text).to_csv ('answer.csv', index= False )

# Ровно по 100 слов если сделать

In [ ]:
# Инициализируем токенизатор для обработки текста
tokenizer = Tokenizer(filters='')
tokenizer.fit_on_texts(X_100_text + Y_100_text + User_X)

# Подготавливаем данные для обучения
source_100 = tokenizer.texts_to_sequences(X_100_text)
target_100 = tokenizer.texts_to_sequences(Y_100_text)

# Определяем максимальную длину последовательности
max_sequence_length = max(len(seq) for seq in source_100+target_100)

# Дополняем последовательности до максимальной длины
source_100_pad = pad_sequences(source_100, maxlen=max_sequence_length, padding='post')
target_100_pad = pad_sequences(target_100, maxlen=max_sequence_length, padding='post')

In [ ]:
# Создаем модель RNN
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=16, input_length=max_sequence_length),
    tf.keras.layers.LSTM(32, return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.word_index) + 1, activation='softmax')#,
    # tf.keras.layers.Lambda(lambda x: tf.argmax(x, axis=2)),
    # tf.keras.layers.Lambda(lambda x: tokenizer.sequences_to_texts(np.array(x)))
])

# Компилируем модель
loss = tf.losses.SparseCategoricalCrossentropy()
# Adadelta - бан, 0
# Adagrad - 0.0361
model.compile(optimizer='Adagrad', loss=loss, metrics=['accuracy'])

# Обучаем модель на исходных и целевых последовательностях
model.fit(np.array(source_100_pad, dtype='int64'), np.round(target_100_pad).astype('int64'), epochs=2000, verbose=2)
model.save('/content/my_model.keras')

Epoch 1/2000
1/1 - 2s - loss: 7.3448 - accuracy: 5.0125e-04 - 2s/epoch - 2s/step
Epoch 2/2000
1/1 - 0s - loss: 7.3448 - accuracy: 5.0125e-04 - 123ms/epoch - 123ms/step
Epoch 3/2000
1/1 - 0s - loss: 7.3448 - accuracy: 5.0125e-04 - 122ms/epoch - 122ms/step
Epoch 4/2000
1/1 - 0s - loss: 7.3447 - accuracy: 5.0125e-04 - 119ms/epoch - 119ms/step
Epoch 5/2000
1/1 - 0s - loss: 7.3447 - accuracy: 0.0010 - 112ms/epoch - 112ms/step
Epoch 6/2000
1/1 - 0s - loss: 7.3447 - accuracy: 0.0010 - 121ms/epoch - 121ms/step
Epoch 7/2000
1/1 - 0s - loss: 7.3447 - accuracy: 0.0010 - 117ms/epoch - 117ms/step
Epoch 8/2000
1/1 - 0s - loss: 7.3447 - accuracy: 0.0010 - 115ms/epoch - 115ms/step
Epoch 9/2000
1/1 - 0s - loss: 7.3447 - accuracy: 0.0010 - 106ms/epoch - 106ms/step
Epoch 10/2000
1/1 - 0s - loss: 7.3447 - accuracy: 0.0010 - 107ms/epoch - 107ms/step
Epoch 11/2000
1/1 - 0s - loss: 7.3446 - accuracy: 0.0010 - 110ms/epoch - 110ms/step
Epoch 12/2000
1/1 - 0s - loss: 7.3446 - accuracy: 0.0010 - 122ms/epoch - 12

# Использование модели



Запустите ячейку ниже

In [ ]:
User_pred = []
for row in User_X:
  seq = tokenizer.texts_to_sequences(row)
  pad_seq = pad_sequences(seq, maxlen=max_sequence_length, padding='post')
  pred = tensor_to_text(model.predict(pad_seq))[0]
  User_pred.append(pred)
User_df = pd.DataFrame(User_pred, columns=['Вывод'])
User_df.to_csv('output.csv')

4/4 [==============================] - 2s 65ms/step


Ваши ответы лежат в файле output.csv
